import std/[
  algorithm, asyncdispatch, atomics, json, locks, macros, math, options, os,
  sets, strutils, tables
]
import mustache
import webui

type
  FrontendCommandKind* = enum
    fckSynchronous
    fckAsynchronous

  FrontendBridgeResponseKind = enum
    fbrAccepted

  FrontendSyncCommand = proc(args: JsonNode): JsonNode {.closure.}
  FrontendAsyncCommand =
    proc(args: JsonNode): Future[JsonNode] {.closure.}

  FrontendCommand = object
    kind: FrontendCommandKind
    syncAdapter: FrontendSyncCommand
    asyncAdapter: FrontendAsyncCommand

  FrontendTypeKind = enum
    ftkVoid
    ftkBoolean
    ftkString
    ftkNumber
    ftkNamed
    ftkSequence
    ftkArray
    ftkOption

  FrontendType = ref object
    kind: FrontendTypeKind
    name: string
    elementType: FrontendType

  BindingParameter = object
    nimName: string
    tsName: string
    parameterType: FrontendType
    hasDefault: bool

  FrontendBinding = object
    commandKind: FrontendCommandKind
    modulePath: string
    nimName: string
    tsName: string
    wireName: string
    parameters: seq[BindingParameter]
    returnType: FrontendType

  FrontendNamedTypeKind = enum
    fntObject
    fntEnum

  FrontendField = object
    name: string
    fieldType: FrontendType

  TypeDeclaration = object
    identity: string
    name: string
    kind: FrontendNamedTypeKind
    fields: seq[FrontendField]
    members: seq[string]

  FrontendBindingsModel = object
    commands: seq[FrontendBinding]
    types: seq[TypeDeclaration]

var
  frontendCommands = initTable[string, FrontendCommand]()
  collectedBindings {.compileTime.}: seq[FrontendBinding]
  collectedTypes {.compileTime.}: seq[TypeDeclaration]
  frontendRequestQueue: Channel[string]
  frontendWakeEvent: AsyncEvent
  frontendWindowOpen: Atomic[bool]
  frontendRuntimeInitialized = false
  frontendLocksInitialized = false
  activeRequestIds = initHashSet[string]()
  activeRequestIdsLock: Lock
  frontendWakeLock: Lock

const GeneratedHeader = "// Generated by Nim {.accessible.}; do not edit.\n"
const MaxSafeJavaScriptInteger = 9_007_199_254_740_991'i64
const FrontendBindingsOutput {.strdefine.} = ""
const FrontendRpcProjectRoot = currentSourcePath().parentDir.parentDir.parentDir
const FrontendRpcMetadataPath =
  FrontendRpcProjectRoot / ".nimcache" / "frontend-rpc.json"
const CommandModuleTemplate = staticRead(
  currentSourcePath().parentDir / "frontend_rpc_templates" / "command.mustache")
const TypesTemplate = staticRead(
  currentSourcePath().parentDir / "frontend_rpc_templates" / "types.mustache")

proc registerFrontendCommand(name: string, command: FrontendCommand) =
  if frontendCommands.hasKey(name):
    raise newException(ValueError,
      "A frontend command named '" & name & "' is already registered")
  frontendCommands[name] = command

proc registerFrontendSyncCommand(name: string, command: FrontendSyncCommand) =
  registerFrontendCommand(name, FrontendCommand(
    kind: fckSynchronous,
    syncAdapter: command
  ))

proc registerFrontendAsyncCommand(
    name: string, command: FrontendAsyncCommand) =
  registerFrontendCommand(name, FrontendCommand(
    kind: fckAsynchronous,
    asyncAdapter: command
  ))

proc frontendFromJson[T](node: JsonNode, _: typedesc[T]): T =
  when T is string:
    if node.kind != JString:
      raise newException(ValueError, "Frontend string value expected")
    result = node.getStr()
  elif T is bool:
    if node.kind != JBool:
      raise newException(ValueError, "Frontend boolean value expected")
    result = node.getBool()
  elif T is SomeInteger:
    if node.kind != JInt:
      raise newException(ValueError, "Frontend integer value expected")
    let value = node.getBiggestInt()
    if value < -MaxSafeJavaScriptInteger or value > MaxSafeJavaScriptInteger:
      raise newException(ValueError,
        "Frontend integers must be within JavaScript's safe integer range")
    when T is SomeUnsignedInt:
      if value < 0:
        raise newException(
          ValueError, "Frontend unsigned integer must be positive")
    when sizeof(T) < 8:
      if value < BiggestInt(low(T)) or value > BiggestInt(high(T)):
        raise newException(
          ValueError, "Frontend integer is outside its Nim range")
    result = T(value)
  elif T is SomeFloat:
    if node.kind notin {JInt, JFloat}:
      raise newException(ValueError, "Frontend number value expected")
    result = T(node.getFloat())
    if classify(result) in {fcNan, fcInf, fcNegInf}:
      raise newException(ValueError,
        "Frontend floating-point values must be finite")
  elif T is enum:
    if node.kind != JString:
      raise newException(ValueError,
        "Frontend enum values must be encoded as symbols")
    result = parseEnum[T](node.getStr())
  elif T is Option:
    type Inner = typeof(default(T).get)
    if node.kind == JNull:
      result = none(Inner)
    else:
      result = some(frontendFromJson(node, Inner))
  elif T is seq:
    type Inner = typeof(default(T)[0])
    if node.kind != JArray:
      raise newException(ValueError, "Frontend sequence values must be arrays")
    for index in 0 ..< node.len:
      result.add(frontendFromJson(node[index], Inner))
  elif T is array:
    type Inner = typeof(default(T)[0])
    if node.kind != JArray or node.len != result.len:
      raise newException(ValueError,
        "Frontend fixed array must contain exactly " & $result.len & " values")
    for index in 0 ..< result.len:
      result[index] = frontendFromJson(node[index], Inner)
  elif T is object:
    if node.kind != JObject:
      raise newException(ValueError, "Frontend object values must be objects")
    for fieldName, field in fieldPairs(result):
      if not node.hasKey(fieldName):
        raise newException(ValueError,
          "Missing required object field '" & fieldName & "'")
      field = frontendFromJson(node[fieldName], typeof(field))
  else:
    {.error: "unsupported frontend input type".}

proc frontendToJson[T](value: T): JsonNode =
  when T is Option:
    if value.isSome:
      result = frontendToJson(value.get)
    else:
      result = newJNull()
  elif T is enum:
    result = %($value)
  elif T is object:
    result = newJObject()
    for fieldName, field in fieldPairs(value):
      result[fieldName] = frontendToJson(field)
  elif T is seq or T is array:
    result = newJArray()
    for item in value:
      result.add(frontendToJson(item))
  elif T is SomeFloat:
    if classify(value) in {fcNan, fcInf, fcNegInf}:
      raise newException(ValueError,
        "Frontend floating-point values must be finite")
    result = %value
  elif T is SomeInteger:
    when T is SomeUnsignedInt:
      if uint64(value) > uint64(MaxSafeJavaScriptInteger):
        raise newException(ValueError,
          "Frontend integers must be within JavaScript's safe integer range")
    else:
      if int64(value) < -MaxSafeJavaScriptInteger or
          int64(value) > MaxSafeJavaScriptInteger:
        raise newException(ValueError,
          "Frontend integers must be within JavaScript's safe integer range")
    result = %value
  elif T is bool or T is string:
    result = %value
  else:
    {.error: "unsupported frontend result type".}

proc commandName(node: NimNode): string {.compileTime.} =
  case node.kind
  of nnkIdent, nnkSym:
    result = node.strVal
  of nnkPostfix:
    result = commandName(node[1])
  else:
    error("frontend only supports normally named procedures", node)

proc callableName(node: NimNode): NimNode {.compileTime.} =
  case node.kind
  of nnkIdent, nnkSym:
    result = node.copyNimTree
  of nnkPostfix:
    result = node[1].copyNimTree
  else:
    error("frontend only supports normally named procedures", node)

proc defaultInAdapterContext(node: NimNode;
    parameterValues: OrderedTable[string, NimNode]): NimNode {.compileTime.} =
  ## Default expressions are copied out of the procedure declaration and into
  ## the generated adapter. Make earlier converted/defaulted parameters
  ## available under their source names, letting Nim resolve identifiers inside
  ## the expression exactly as it normally would (including field names and
  ## nested scopes).
  result = newNimNode(nnkStmtListExpr)
  for name, value in parameterValues:
    result.add(newLetStmt(newIdentNode(name), value.copyNimTree))

  proc copyWithAdapterParameters(current: NimNode): NimNode =
    if current.kind == nnkSym and parameterValues.hasKey(current.strVal):
      return newIdentNode(current.strVal)
    result = current.copyNimNode
    for child in current:
      result.add(copyWithAdapterParameters(child))

  result.add(copyWithAdapterParameters(node))

proc lowerCamelCase(name: string): string {.compileTime.} =
  var uppercaseNext = false
  for character in name:
    if character == '_':
      uppercaseNext = true
    elif result.len == 0:
      result.add(character.toLowerAscii())
      uppercaseNext = false
    elif uppercaseNext:
      result.add(character.toUpperAscii())
      uppercaseNext = false
    else:
      result.add(character)

  if result.len == 0:
    error("frontend names cannot consist only of underscores")

proc isExportedName(node: NimNode): bool {.compileTime.} =
  node.kind == nnkPostfix and node.len == 2 and node[0].strVal == "*"

proc commandsDirectory(): string {.compileTime.} =
  currentSourcePath().parentDir.parentDir / "commands"

proc modulePathFor(filename: string): string {.compileTime.} =
  let
    source = filename.normalizedPath
    root = commandsDirectory().normalizedPath
    relative = source.relativePath(root)

  if relative != ".." and not relative.startsWith("../") and
      not relative.startsWith(".." & $DirSep):
    result = relative.changeFileExt("").replace(DirSep, '/')
  else:
    let
      portableSource = source.replace(DirSep, '/')
      commandsMarker = "/commands/"
      markerIndex = portableSource.rfind(commandsMarker)
    if markerIndex >= 0:
      result = portableSource[
        markerIndex + commandsMarker.len .. ^1].changeFileExt("")
    else:
      result = source.extractFilename.changeFileExt("")

proc typeIdentity(symbol: NimNode): string {.compileTime.} =
  let location = symbol.getImpl.lineInfoObj
  result = location.filename.normalizedPath & ":" &
    $location.line & ":" & symbol.strVal

proc findType(identity: string): int {.compileTime.} =
  for index, declaration in collectedTypes:
    if declaration.identity == identity:
      return index
  result = -1

proc ensureNamedType(typeNode: NimNode): string {.compileTime.}

proc unsupportedType(typeNode: NimNode; detail = "") {.compileTime.} =
  var message = "unsupported frontend type '" & typeNode.repr & "'"
  if detail.len > 0:
    message.add(": " & detail)
  error(message, typeNode)

proc frontendType(typeNode: NimNode): FrontendType {.compileTime.} =
  if typeNode.kind == nnkEmpty:
    return FrontendType(kind: ftkVoid)

  let node =
    if typeNode.kind == nnkVarTy: typeNode[0]
    else: typeNode

  case node.kind
  of nnkBracketExpr:
    let container = node[0].strVal
    case container
    of "seq":
      if node.len != 2:
        unsupportedType(node)
      result = FrontendType(
        kind: ftkSequence,
        elementType: frontendType(node[1])
      )
    of "array":
      if node.len != 3:
        unsupportedType(node)
      result = FrontendType(
        kind: ftkArray,
        elementType: frontendType(node[2])
      )
    of "Option":
      if node.len != 2:
        unsupportedType(node)
      result = FrontendType(
        kind: ftkOption,
        elementType: frontendType(node[1])
      )
    else:
      unsupportedType(node,
        "generics are not part of the frontend binding contract")
  of nnkSym, nnkIdent:
    let name = node.strVal
    case name
    of "void":
      result = FrontendType(kind: ftkVoid)
    of "bool":
      result = FrontendType(kind: ftkBoolean)
    of "string":
      result = FrontendType(kind: ftkString)
    of "int", "int8", "int16", "int32", "int64",
        "uint", "uint8", "uint16", "uint32", "uint64",
        "Natural", "Positive", "float", "float32", "float64":
      result = FrontendType(kind: ftkNumber)
    else:
      if node.kind != nnkSym:
        unsupportedType(node, "the type could not be resolved")
      let typeName = ensureNamedType(node)
      result = FrontendType(kind: ftkNamed, name: typeName)
  of nnkTupleTy, nnkTupleConstr:
    unsupportedType(node, "tuples are not supported")
  of nnkRefTy:
    unsupportedType(node, "reference types are not supported")
  of nnkPtrTy:
    unsupportedType(node, "pointer types are not supported")
  else:
    unsupportedType(node)

proc futureValueType(typeNode: NimNode): NimNode {.compileTime.} =
  let node =
    if typeNode.kind == nnkVarTy: typeNode[0]
    else: typeNode

  if node.kind == nnkBracketExpr and node.len == 2 and
      node[0].sameType(bindSym"Future"):
    return node[1]

  if node.kind == nnkSym:
    let definition = node.getImpl
    if definition.kind == nnkTypeDef:
      return futureValueType(definition[2])

  result = newEmptyNode()

proc enumMemberName(node: NimNode): string {.compileTime.} =
  case node.kind
  of nnkIdent, nnkSym:
    result = node.strVal
  of nnkEnumFieldDef:
    result = node[0].strVal
  else:
    error("unsupported enum member in frontend type", node)

proc ensureNamedType(typeNode: NimNode): string {.compileTime.} =
  let
    identity = typeIdentity(typeNode)
    existingIndex = findType(identity)

  if existingIndex >= 0:
    return collectedTypes[existingIndex].name

  let definition = typeNode.getImpl
  if definition.kind != nnkTypeDef:
    unsupportedType(typeNode)
  if not isExportedName(definition[0]):
    error("frontend object and enum types must be exported: '" &
      typeNode.strVal & "'", typeNode)

  let
    typeName = typeNode.strVal
    body = definition[2]

  for declaration in collectedTypes:
    if declaration.name == typeName and declaration.identity != identity:
      error("ambiguous frontend type name '" & typeName &
        "' is declared in more than one module", typeNode)

  # Install a placeholder first so recursive object fields terminate.
  collectedTypes.add(TypeDeclaration(identity: identity, name: typeName))
  let declarationIndex = collectedTypes.high

  case body.kind
  of nnkEnumTy:
    collectedTypes[declarationIndex].kind = fntEnum
    for index in 1 ..< body.len:
      collectedTypes[declarationIndex].members.add(
        enumMemberName(body[index]))
    if collectedTypes[declarationIndex].members.len == 0:
      error("frontend enums must contain at least one member", typeNode)
  of nnkObjectTy:
    collectedTypes[declarationIndex].kind = fntObject
    if body[1].kind != nnkEmpty:
      error("frontend objects cannot use inheritance", typeNode)
    let fields = body[2]
    if fields.kind != nnkRecList:
      error("unsupported frontend object layout for '" & typeName & "'",
        typeNode)

    for field in fields:
      if field.kind != nnkIdentDefs:
        error("frontend objects cannot contain variants or case fields",
          field)
      if field[^1].kind != nnkEmpty:
        error("frontend object fields cannot have default values", field)
      for nameIndex in 0 ..< field.len - 2:
        let fieldNameNode = field[nameIndex]
        if not isExportedName(fieldNameNode):
          error("frontend object field '" & commandName(fieldNameNode) &
            "' must be exported", fieldNameNode)
        let
          fieldName = commandName(fieldNameNode)
          fieldType = frontendType(field[^2])
        collectedTypes[declarationIndex].fields.add(
          FrontendField(name: fieldName, fieldType: fieldType))
  else:
    unsupportedType(typeNode,
      "only exported enums and plain objects are supported as named types")

  result = typeName

macro collectFrontendBinding*(target: typed; modulePath, nimName,
    wireName: static[string]; commandKind: static[FrontendCommandKind]): untyped =
  let definition = target.getImpl
  if definition.kind != nnkProcDef:
    error("frontend binding metadata requires a procedure", target)

  let formalParams = definition[3]
  var
    binding = FrontendBinding(
      commandKind: commandKind,
      modulePath: modulePath,
      nimName: nimName,
      tsName: lowerCamelCase(nimName),
      wireName: wireName
    )
    tsParameterNames = initHashSet[string]()

  for index in 1 ..< formalParams.len:
    let parameter = formalParams[index]
    if parameter.kind != nnkIdentDefs:
      error("unsupported frontend command parameter", parameter)
    for nameIndex in 0 ..< parameter.len - 2:
      let
        originalName = parameter[nameIndex].strVal
        tsName = lowerCamelCase(originalName)
      if tsName in tsParameterNames:
        error("frontend parameter name collision after lowerCamelCase: '" &
          tsName & "'", parameter[nameIndex])
      tsParameterNames.incl(tsName)
      binding.parameters.add(BindingParameter(
        nimName: originalName,
        tsName: tsName,
        parameterType: frontendType(parameter[^2]),
        hasDefault: parameter[^1].kind != nnkEmpty
      ))

  let futureType = futureValueType(formalParams[0])
  binding.returnType = frontendType(
    if commandKind == fckAsynchronous: futureType
    else: formalParams[0]
  )

  for existing in collectedBindings:
    if existing.modulePath == binding.modulePath and
        existing.tsName == binding.tsName:
      error("frontend command name collision after lowerCamelCase in module '" &
        binding.modulePath & "': '" & binding.tsName & "'", target)
    if existing.wireName == binding.wireName:
      error("duplicate frontend wire name '" & binding.wireName & "'", target)

  collectedBindings.add(binding)
  result = newEmptyNode()

macro createFrontendCommandAdapter(target: typed; modulePath, nimName,
    wireName: static[string]): untyped =
  let
    definition = target.getImpl
    formalParams = definition[3]
    futureType = futureValueType(formalParams[0])
    commandKind =
      if futureType.kind == nnkEmpty: fckSynchronous
      else: fckAsynchronous
    argsNode = genSym(nskParam, "args")

  var
    adapterBody = newStmtList()
    call = newCall(target)
    parameterValues = initOrderedTable[string, NimNode]()

  for index in 1 ..< formalParams.len:
    let parameter = formalParams[index]
    if parameter.kind != nnkIdentDefs:
      error("unsupported frontend command parameter", parameter)

    let parameterType = parameter[^2]
    if parameterType.kind == nnkEmpty:
      error("accessible command parameters need an explicit type", parameter)
    let parameterTypeDescriptor =
      newTree(nnkBracketExpr, bindSym"typedesc", parameterType)

    for nameIndex in 0 ..< parameter.len - 2:
      let
        parameterNode = parameter[nameIndex]
        parameterName = commandName(parameterNode)
        parameterNameLiteral = newLit(parameterName)
        localValue = genSym(nskLet, parameterName)

      if parameter[^1].kind == nnkEmpty:
        adapterBody.add quote do:
          if not `argsNode`.hasKey(`parameterNameLiteral`):
            raise newException(ValueError,
              "Missing required argument '" & `parameterNameLiteral` & "'")
          let `localValue` = frontendFromJson(
            `argsNode`[`parameterNameLiteral`], `parameterTypeDescriptor`)
      else:
        let defaultValue =
          defaultInAdapterContext(parameter[^1], parameterValues)
        adapterBody.add quote do:
          let `localValue`: `parameterType` =
            if `argsNode`.hasKey(`parameterNameLiteral`):
              frontendFromJson(
                `argsNode`[`parameterNameLiteral`],
                `parameterTypeDescriptor`)
            else:
              `defaultValue`

      call.add(localValue)
      parameterValues[parameterName] = localValue

  result = newStmtList()
  result.add newCall(bindSym"collectFrontendBinding", target,
    newLit(modulePath), newLit(nimName), newLit(wireName),
    newLit(commandKind))

  if commandKind == fckAsynchronous:
    if futureType.kind == nnkEmpty:
      error("internal error resolving asynchronous frontend result", target)
    elif futureType.strVal == "void":
      adapterBody.add quote do:
        await `call`
        result = newJNull()
    else:
      let value = genSym(nskLet, "value")
      adapterBody.add quote do:
        let `value` = await `call`
        result = frontendToJson(`value`)

    result.add quote do:
      registerFrontendAsyncCommand(
        `wireName`,
        proc(`argsNode`: JsonNode): Future[JsonNode] {.async.} =
          `adapterBody`
      )
  else:
    if formalParams[0].kind == nnkEmpty:
      adapterBody.add(call)
      adapterBody.add quote do:
        result = newJNull()
    else:
      adapterBody.add quote do:
        result = frontendToJson(`call`)

    result.add quote do:
      registerFrontendSyncCommand(
        `wireName`,
        proc(`argsNode`: JsonNode): JsonNode =
          `adapterBody`
      )

macro accessible*(definition: untyped): untyped =
  ## Exposes a typed procedure through the frontend command registry and
  ## records its resolved signature for TypeScript generation.
  if definition.kind != nnkProcDef:
    error("accessible can only be applied to a procedure", definition)

  let genericParams = definition[2]
  if genericParams.kind != nnkEmpty and genericParams.len > 0:
    error("accessible commands cannot be generic", genericParams)

  let
    nimName = commandName(definition[0])
    target = callableName(definition[0])
    modulePath = modulePathFor(definition.lineInfoObj.filename)
    wireName = modulePath.replace('/', '.') & "." & nimName
  result = newStmtList(definition)
  result.add newCall(bindSym"createFrontendCommandAdapter", target,
    newLit(modulePath), newLit(nimName), newLit(wireName))

proc frontendTypeKindName(kind: FrontendTypeKind): string =
  case kind
  of ftkVoid: "void"
  of ftkBoolean: "boolean"
  of ftkString: "string"
  of ftkNumber: "number"
  of ftkNamed: "named"
  of ftkSequence: "sequence"
  of ftkArray: "array"
  of ftkOption: "option"

proc namedTypeKindName(kind: FrontendNamedTypeKind): string =
  case kind
  of fntObject: "object"
  of fntEnum: "enum"

proc commandKindName(kind: FrontendCommandKind): string =
  case kind
  of fckSynchronous: "synchronous"
  of fckAsynchronous: "asynchronous"

proc parseCommandKind(name, path: string): FrontendCommandKind =
  case name
  of "synchronous": fckSynchronous
  of "asynchronous": fckAsynchronous
  else:
    raise newException(ValueError,
      "Invalid frontend RPC metadata: unknown command kind '" & name &
      "' at " & path)

proc bridgeResponseKindName(kind: FrontendBridgeResponseKind): string =
  case kind
  of fbrAccepted: "accepted"

proc frontendTypeJson(frontendType: FrontendType): JsonNode =
  result = newJObject()
  result["kind"] = %frontendTypeKindName(frontendType.kind)
  case frontendType.kind
  of ftkNamed:
    result["name"] = %frontendType.name
  of ftkSequence, ftkArray, ftkOption:
    result["elementType"] = frontendTypeJson(frontendType.elementType)
  else:
    discard

proc frontendBindingsJson(model: FrontendBindingsModel): JsonNode =
  result = newJObject()
  result["schemaVersion"] = %2
  result["commands"] = newJArray()
  for binding in model.commands:
    var command = newJObject()
    command["commandKind"] = %commandKindName(binding.commandKind)
    command["modulePath"] = %binding.modulePath
    command["nimName"] = %binding.nimName
    command["tsName"] = %binding.tsName
    command["wireName"] = %binding.wireName
    command["parameters"] = newJArray()
    for parameter in binding.parameters:
      var parameterNode = newJObject()
      parameterNode["nimName"] = %parameter.nimName
      parameterNode["tsName"] = %parameter.tsName
      parameterNode["hasDefault"] = %parameter.hasDefault
      parameterNode["type"] = frontendTypeJson(parameter.parameterType)
      command["parameters"].add(parameterNode)
    command["returnType"] = frontendTypeJson(binding.returnType)
    result["commands"].add(command)

  result["types"] = newJArray()
  for declaration in model.types:
    var typeNode = newJObject()
    typeNode["name"] = %declaration.name
    typeNode["kind"] = %namedTypeKindName(declaration.kind)
    case declaration.kind
    of fntObject:
      typeNode["fields"] = newJArray()
      for field in declaration.fields:
        var fieldNode = newJObject()
        fieldNode["name"] = %field.name
        fieldNode["type"] = frontendTypeJson(field.fieldType)
        typeNode["fields"].add(fieldNode)
    of fntEnum:
      typeNode["members"] = %declaration.members
    result["types"].add(typeNode)

proc relativeImport(modulePath, target: string): string =
  let depth = modulePath.count('/')
  result = "../".repeat(depth + 1) & target

proc relativeTypesImport(modulePath: string): string =
  let depth = modulePath.count('/')
  if depth == 0:
    result = "./types"
  else:
    result = "../".repeat(depth) & "types"

proc frontendBindingsOutputDirectory(): string =
  result =
    if FrontendBindingsOutput.len > 0: FrontendBindingsOutput
    else: FrontendRpcProjectRoot / "frontend" / "commands"

proc safeGeneratedPath(relativePath: string): bool =
  if relativePath.len == 0 or relativePath.isAbsolute or
      not relativePath.endsWith(".ts"):
    return false
  for component in relativePath.split({'/', '\\'}):
    if component.len == 0 or component == "." or component == "..":
      return false
  result = true

proc renderedManifest(files: openArray[(string, string)]): string =
  var expectedPaths: seq[string]
  for item in files:
    if not safeGeneratedPath(item[0]):
      raise newException(ValueError,
        "Refusing unsafe generated frontend path '" & item[0] & "'")
    expectedPaths.add(item[0])
  expectedPaths.sort()
  result = GeneratedHeader & expectedPaths.join("\n") & "\n"

proc updateGeneratedFiles(files: openArray[(string, string)]) =
  let
    outputDirectory = frontendBindingsOutputDirectory()
    manifestPath = outputDirectory / ".frontend-bindings-manifest"
    manifest = renderedManifest(files)
  var expectedPaths: seq[string]

  for item in files:
    expectedPaths.add(item[0])
  expectedPaths.sort()

  createDir(outputDirectory)

  var stalePaths: seq[string]
  if fileExists(manifestPath):
    for line in readFile(manifestPath).splitLines:
      if safeGeneratedPath(line) and line notin expectedPaths:
        stalePaths.add(line)

  for stalePath in stalePaths:
    let destination = outputDirectory / stalePath
    if fileExists(destination):
      removeFile(destination)

  for item in files:
    let destination = outputDirectory / item[0]
    createDir(destination.parentDir)
    if not fileExists(destination) or readFile(destination) != item[1]:
      writeFile(destination, item[1])

  if not fileExists(manifestPath) or readFile(manifestPath) != manifest:
    writeFile(manifestPath, manifest)

proc requireField(node: JsonNode; name, path: string;
    kind: JsonNodeKind): JsonNode =
  if node.kind != JObject or not node.hasKey(name):
    raise newException(ValueError,
      "Invalid frontend RPC metadata: missing " & path & "." & name)
  result = node[name]
  if result.kind != kind:
    raise newException(ValueError,
      "Invalid frontend RPC metadata: " & path & "." & name &
      " has the wrong JSON type")

proc parseFrontendType(node: JsonNode; path: string): FrontendType =
  let kindName = requireField(node, "kind", path, JString).getStr()
  case kindName
  of "void":
    result = FrontendType(kind: ftkVoid)
  of "boolean":
    result = FrontendType(kind: ftkBoolean)
  of "string":
    result = FrontendType(kind: ftkString)
  of "number":
    result = FrontendType(kind: ftkNumber)
  of "named":
    result = FrontendType(
      kind: ftkNamed,
      name: requireField(node, "name", path, JString).getStr()
    )
  of "sequence", "array", "option":
    let element = requireField(node, "elementType", path, JObject)
    let kind =
      case kindName
      of "sequence": ftkSequence
      of "array": ftkArray
      else: ftkOption
    result = FrontendType(
      kind: kind,
      elementType: parseFrontendType(element, path & ".elementType")
    )
  else:
    raise newException(ValueError,
      "Invalid frontend RPC metadata: unknown type kind '" & kindName & "'")

proc readFrontendBindingsModel(): FrontendBindingsModel =
  if not fileExists(FrontendRpcMetadataPath):
    raise newException(IOError,
      "Frontend RPC metadata is missing. Run `./app.sh serialize` first.")

  let root =
    try:
      parseJson(readFile(FrontendRpcMetadataPath))
    except JsonParsingError as exception:
      raise newException(ValueError,
        "Invalid frontend RPC metadata JSON: " & exception.msg)

  let schemaVersion = requireField(
    root, "schemaVersion", "root", JInt).getInt()
  if schemaVersion != 2:
    raise newException(ValueError,
      "Unsupported frontend RPC metadata schema version " & $schemaVersion)

  let commands = requireField(root, "commands", "root", JArray)
  for index in 0 ..< commands.len:
    let commandNode = commands[index]
    let path = "commands[" & $index & "]"
    var binding = FrontendBinding(
      commandKind: parseCommandKind(
        requireField(commandNode, "commandKind", path, JString).getStr(),
        path & ".commandKind"),
      modulePath: requireField(
        commandNode, "modulePath", path, JString).getStr(),
      nimName: requireField(commandNode, "nimName", path, JString).getStr(),
      tsName: requireField(commandNode, "tsName", path, JString).getStr(),
      wireName: requireField(commandNode, "wireName", path, JString).getStr(),
      returnType: parseFrontendType(
        requireField(commandNode, "returnType", path, JObject),
        path & ".returnType")
    )
    let parameters = requireField(
      commandNode, "parameters", path, JArray)
    for parameterIndex in 0 ..< parameters.len:
      let parameterNode = parameters[parameterIndex]
      let parameterPath =
        path & ".parameters[" & $parameterIndex & "]"
      binding.parameters.add(BindingParameter(
        nimName: requireField(
          parameterNode, "nimName", parameterPath, JString).getStr(),
        tsName: requireField(
          parameterNode, "tsName", parameterPath, JString).getStr(),
        hasDefault: requireField(
          parameterNode, "hasDefault", parameterPath, JBool).getBool(),
        parameterType: parseFrontendType(
          requireField(parameterNode, "type", parameterPath, JObject),
          parameterPath & ".type")
      ))
    result.commands.add(binding)

  let types = requireField(root, "types", "root", JArray)
  for index in 0 ..< types.len:
    let typeNode = types[index]
    let
      path = "types[" & $index & "]"
      kindName = requireField(typeNode, "kind", path, JString).getStr()
    var declaration = TypeDeclaration(
      name: requireField(typeNode, "name", path, JString).getStr()
    )
    case kindName
    of "object":
      declaration.kind = fntObject
      let fields = requireField(typeNode, "fields", path, JArray)
      for fieldIndex in 0 ..< fields.len:
        let fieldNode = fields[fieldIndex]
        let fieldPath = path & ".fields[" & $fieldIndex & "]"
        declaration.fields.add(FrontendField(
          name: requireField(
            fieldNode, "name", fieldPath, JString).getStr(),
          fieldType: parseFrontendType(
            requireField(fieldNode, "type", fieldPath, JObject),
            fieldPath & ".type")
        ))
    of "enum":
      declaration.kind = fntEnum
      let members = requireField(typeNode, "members", path, JArray)
      for memberIndex in 0 ..< members.len:
        let member = members[memberIndex]
        if member.kind != JString:
          raise newException(ValueError,
            "Invalid frontend RPC metadata: " & path & ".members[" &
            $memberIndex & "] has the wrong JSON type")
        declaration.members.add(member.getStr())
    else:
      raise newException(ValueError,
        "Invalid frontend RPC metadata: unknown named type kind '" &
        kindName & "'")
    result.types.add(declaration)

proc typeScriptType(frontendType: FrontendType): string =
  case frontendType.kind
  of ftkVoid: "void"
  of ftkBoolean: "boolean"
  of ftkString: "string"
  of ftkNumber: "number"
  of ftkNamed: frontendType.name
  of ftkSequence, ftkArray:
    typeScriptType(frontendType.elementType) & "[]"
  of ftkOption:
    typeScriptType(frontendType.elementType) & " | null"

proc validateFrontendType(frontendType: FrontendType;
    namedTypes: HashSet[string]; allowVoid: bool; path: string) =
  case frontendType.kind
  of ftkVoid:
    if not allowVoid:
      raise newException(ValueError,
        "Invalid frontend RPC metadata: void is not allowed at " & path)
  of ftkNamed:
    if frontendType.name.len == 0 or frontendType.name notin namedTypes:
      raise newException(ValueError,
        "Invalid frontend RPC metadata: unknown named type '" &
        frontendType.name & "' at " & path)
  of ftkSequence, ftkArray, ftkOption:
    validateFrontendType(
      frontendType.elementType, namedTypes, false, path & ".elementType")
  else:
    discard

proc validateFrontendBindingsModel(model: FrontendBindingsModel) =
  var
    namedTypes = initHashSet[string]()
    wireNames = initHashSet[string]()
    moduleCommandNames = initHashSet[string]()

  for typeIndex, declaration in model.types:
    if declaration.name.len == 0 or declaration.name in namedTypes:
      raise newException(ValueError,
        "Invalid frontend RPC metadata: duplicate or empty type name at types[" &
        $typeIndex & "]")
    namedTypes.incl(declaration.name)

  for typeIndex, declaration in model.types:
    let path = "types[" & $typeIndex & "]"
    case declaration.kind
    of fntObject:
      var fieldNames = initHashSet[string]()
      for fieldIndex, field in declaration.fields:
        if field.name.len == 0 or field.name in fieldNames:
          raise newException(ValueError,
            "Invalid frontend RPC metadata: duplicate or empty field name at " &
            path & ".fields[" & $fieldIndex & "]")
        fieldNames.incl(field.name)
        validateFrontendType(
          field.fieldType, namedTypes, false,
          path & ".fields[" & $fieldIndex & "].type")
    of fntEnum:
      if declaration.members.len == 0:
        raise newException(ValueError,
          "Invalid frontend RPC metadata: enum " & declaration.name &
          " has no members")
      var members = initHashSet[string]()
      for memberIndex, member in declaration.members:
        if member.len == 0 or member in members:
          raise newException(ValueError,
            "Invalid frontend RPC metadata: duplicate or empty enum member at " &
            path & ".members[" & $memberIndex & "]")
        members.incl(member)

  for commandIndex, binding in model.commands:
    let
      path = "commands[" & $commandIndex & "]"
      outputPath = binding.modulePath & ".ts"
      moduleCommandName = binding.modulePath & "\0" & binding.tsName
    if binding.modulePath.len == 0 or not safeGeneratedPath(outputPath):
      raise newException(ValueError,
        "Invalid frontend RPC metadata: unsafe module path at " & path)
    if binding.nimName.len == 0 or binding.tsName.len == 0 or
        binding.wireName.len == 0:
      raise newException(ValueError,
        "Invalid frontend RPC metadata: empty command name at " & path)
    if binding.wireName in wireNames:
      raise newException(ValueError,
        "Invalid frontend RPC metadata: duplicate wire name '" &
        binding.wireName & "'")
    if moduleCommandName in moduleCommandNames:
      raise newException(ValueError,
        "Invalid frontend RPC metadata: duplicate TypeScript command '" &
        binding.tsName & "' in module '" & binding.modulePath & "'")
    wireNames.incl(binding.wireName)
    moduleCommandNames.incl(moduleCommandName)

    var
      parameterNames = initHashSet[string]()
      parameterTsNames = initHashSet[string]()
    for parameterIndex, parameter in binding.parameters:
      if parameter.nimName.len == 0 or parameter.tsName.len == 0 or
          parameter.nimName in parameterNames or
          parameter.tsName in parameterTsNames:
        raise newException(ValueError,
          "Invalid frontend RPC metadata: duplicate or empty parameter at " &
          path & ".parameters[" & $parameterIndex & "]")
      parameterNames.incl(parameter.nimName)
      parameterTsNames.incl(parameter.tsName)
      validateFrontendType(
        parameter.parameterType, namedTypes, false,
        path & ".parameters[" & $parameterIndex & "].type")
    validateFrontendType(
      binding.returnType, namedTypes, true, path & ".returnType")

proc collectReferencedTypeNames(frontendType: FrontendType;
    names: var seq[string]) =
  case frontendType.kind
  of ftkNamed:
    if frontendType.name notin names:
      names.add(frontendType.name)
  of ftkSequence, ftkArray, ftkOption:
    collectReferencedTypeNames(frontendType.elementType, names)
  else:
    discard

proc renderCommandModule(modulePath: string;
    bindings: seq[FrontendBinding]): string =
  var referencedTypes: seq[string]
  for binding in bindings:
    for parameter in binding.parameters:
      collectReferencedTypeNames(parameter.parameterType, referencedTypes)
    collectReferencedTypeNames(binding.returnType, referencedTypes)
  referencedTypes.sort()

  var commandViews = newJArray()
  for bindingIndex, binding in bindings:
    var
      parameterDeclarations: seq[string]
      argumentFields: seq[string]
    for parameterIndex, parameter in binding.parameters:
      let parameterType = typeScriptType(parameter.parameterType)
      if parameter.hasDefault:
        var hasRequiredParameterAfter = false
        for laterIndex in parameterIndex + 1 ..< binding.parameters.len:
          if not binding.parameters[laterIndex].hasDefault:
            hasRequiredParameterAfter = true
            break
        if hasRequiredParameterAfter:
          parameterDeclarations.add(
            parameter.tsName & ": " & parameterType & " | undefined")
        else:
          parameterDeclarations.add(
            parameter.tsName & "?: " & parameterType)
      else:
        parameterDeclarations.add(parameter.tsName & ": " & parameterType)
      if parameter.nimName == parameter.tsName:
        argumentFields.add(parameter.tsName)
      else:
        argumentFields.add(parameter.nimName & ": " & parameter.tsName)

    commandViews.add(%* {
      "tsName": binding.tsName,
      "parameters": parameterDeclarations.join(", "),
      "returnType": typeScriptType(binding.returnType),
      "wireName": binding.wireName,
      "arguments": argumentFields.join(", "),
      "last": bindingIndex == bindings.high,
    })

  let context = newContext()
  context["hasTypeImports"] = referencedTypes.len > 0
  context["typeImports"] = referencedTypes.join(", ")
  context["typesImport"] = relativeTypesImport(modulePath)
  context["rpcImport"] = relativeImport(modulePath, "rpc")
  context["commands"] = commandViews
  result = CommandModuleTemplate.render(context)

proc renderTypesFile(types: seq[TypeDeclaration]): string =
  var typeViews = newJArray()
  for typeIndex, declaration in types:
    var typeView = %* {
      "name": declaration.name,
      "isObject": declaration.kind == fntObject,
      "isEnum": declaration.kind == fntEnum,
      "last": typeIndex == types.high,
    }
    case declaration.kind
    of fntObject:
      typeView["fields"] = newJArray()
      for field in declaration.fields:
        typeView["fields"].add(%* {
          "name": field.name,
          "type": typeScriptType(field.fieldType),
        })
    of fntEnum:
      var members: seq[string]
      for member in declaration.members:
        members.add("'" & member & "'")
      typeView["members"] = %members.join(" | ")
    typeViews.add(typeView)

  let context = newContext()
  context["hasTypes"] = types.len > 0
  context["types"] = typeViews
  result = TypesTemplate.render(context)

proc generateFrontendFiles() =
  let model = readFrontendBindingsModel()
  validateFrontendBindingsModel(model)
  var
    files: seq[(string, string)]
    modulePaths: seq[string]
  for binding in model.commands:
    if binding.modulePath notin modulePaths:
      modulePaths.add(binding.modulePath)
  modulePaths.sort()

  for modulePath in modulePaths:
    var moduleBindings: seq[FrontendBinding]
    for binding in model.commands:
      if binding.modulePath == modulePath:
        moduleBindings.add(binding)
    files.add((modulePath & ".ts",
      renderCommandModule(modulePath, moduleBindings)))

  files.add(("types.ts", renderTypesFile(model.types)))
  files.sort(proc(left, right: (string, string)): int =
    cmp(left[0], right[0]))
  updateGeneratedFiles(files)

proc updateSerializedFrontendBindings(contents: string) =
  createDir(FrontendRpcMetadataPath.parentDir)
  if not fileExists(FrontendRpcMetadataPath) or
      readFile(FrontendRpcMetadataPath) != contents:
    writeFile(FrontendRpcMetadataPath, contents)

macro defineFrontendBindings*(): untyped =
  var bindings = collectedBindings
  bindings.sort(proc(left, right: FrontendBinding): int =
    result = cmp((left.modulePath, left.tsName), (right.modulePath, right.tsName))
  )

  var types = collectedTypes
  types.sort(proc(left, right: TypeDeclaration): int =
    result = cmp(left.name, right.name)
  )
  let serializedModel = newLit($(frontendBindingsJson(
    FrontendBindingsModel(commands: bindings, types: types))))
  result = quote do:
    proc serializeFrontendBindings*() =
      updateSerializedFrontendBindings(`serializedModel`)

    proc generateFrontendBindings*() =
      generateFrontendFiles()

proc errorResponse(message: string): string =
  $(%* {"ok": false, "error": message})

proc asyncErrorMessage(exception: ref Exception): string =
  const TracebackMarker = "\nAsync traceback:"
  let markerIndex = exception.msg.find(TracebackMarker)
  if markerIndex >= 0:
    result = exception.msg[0 ..< markerIndex]
  else:
    result = exception.msg

proc frontendRequest(requestJson: string): tuple[
    request: JsonNode, commandName: string, args: JsonNode] =
  let request = parseJson(requestJson)
  if request.kind != JObject:
    raise newException(ValueError, "Request must be a JSON object")
  if not request.hasKey("command") or request["command"].kind != JString:
    raise newException(ValueError, "Request field 'command' must be a string")

  let args = if request.hasKey("args"): request["args"] else: newJObject()
  if args.kind != JObject:
    raise newException(ValueError, "Request field 'args' must be a JSON object")

  result = (request, request["command"].getStr(), args)

proc dispatchFrontendRequest*(requestJson: string): string =
  ## Dispatches one JSON request. Exported so the protocol can be tested
  ## without opening a browser window.
  try:
    let (_, commandName, args) = frontendRequest(requestJson)
    if not frontendCommands.hasKey(commandName):
      return errorResponse("Unknown frontend command '" & commandName & "'")

    let command = frontendCommands[commandName]
    if command.kind == fckAsynchronous:
      return errorResponse(
        "Frontend command '" & commandName & "' is asynchronous; use " &
        "dispatchFrontendRequestAsync")

    let value = command.syncAdapter(args)
    result = $(%* {"ok": true, "value": value})
  except CatchableError as exception:
    result = errorResponse(exception.msg)

proc dispatchFrontendRequestAsync*(
    requestJson: string): Future[string] {.async.} =
  ## Dispatches either command kind on the current async dispatcher.
  try:
    let (_, commandName, args) = frontendRequest(requestJson)
    if not frontendCommands.hasKey(commandName):
      return errorResponse("Unknown frontend command '" & commandName & "'")

    let command = frontendCommands[commandName]
    let value =
      case command.kind
      of fckSynchronous:
        command.syncAdapter(args)
      of fckAsynchronous:
        await command.asyncAdapter(args)
    result = $(%* {"ok": true, "value": value})
  except CatchableError as exception:
    result = errorResponse(asyncErrorMessage(exception))

proc requestId(request: JsonNode): string =
  if not request.hasKey("requestId") or request["requestId"].kind != JString:
    raise newException(
      ValueError, "Request field 'requestId' must be a string")
  result = request["requestId"].getStr()
  if result.len == 0:
    raise newException(
      ValueError, "Request field 'requestId' must not be empty")

proc reserveRequestId(requestId: string): bool =
  acquire(activeRequestIdsLock)
  try:
    if requestId notin activeRequestIds:
      activeRequestIds.incl(requestId)
      result = true
  finally:
    release(activeRequestIdsLock)

proc releaseRequestId(requestId: string) =
  acquire(activeRequestIdsLock)
  try:
    activeRequestIds.excl(requestId)
  finally:
    release(activeRequestIdsLock)

proc queueFrontendRequest(requestJson: string): bool =
  acquire(frontendWakeLock)
  try:
    if not frontendRuntimeInitialized or
        not frontendWindowOpen.load(moAcquire):
      return false
    frontendRequestQueue.send(requestJson)
    frontendWakeEvent.trigger()
    result = true
  finally:
    release(frontendWakeLock)

proc acceptedResponse(requestId: string): string =
  $(%* {
    "kind": bridgeResponseKindName(fbrAccepted),
    "requestId": requestId,
  })

proc completionScript(requestId, response: string): string =
  let arguments = %*[requestId, parseJson(response)]
  result = "window.__nimriRpcComplete?.(..." & $arguments & ");"

proc completeFrontendRequest(
    window: Window, requestId: string, response: Future[string]) =
  releaseRequestId(requestId)

  let responseJson =
    if response.failed:
      errorResponse(asyncErrorMessage(response.error))
    else:
      response.read

  acquire(frontendWakeLock)
  try:
    if frontendRuntimeInitialized and frontendWindowOpen.load(moAcquire):
      window.run(completionScript(requestId, responseJson))
  finally:
    release(frontendWakeLock)

proc startQueuedFrontendRequests(window: Window) =
  while true:
    let queued = frontendRequestQueue.tryRecv()
    if not queued.dataAvailable:
      break

    var queuedRequestId = ""
    try:
      let (request, _, _) = frontendRequest(queued.msg)
      queuedRequestId = requestId(request)
      let response = dispatchFrontendRequestAsync(queued.msg)
      let completionRequestId = queuedRequestId
      response.addCallback(proc() {.gcsafe.} =
        {.cast(gcsafe).}:
          completeFrontendRequest(window, completionRequestId, response)
      )
    except CatchableError as exception:
      if queuedRequestId.len > 0:
        let failedResponse = newFuture[string]("startQueuedFrontendRequests")
        failedResponse.complete(errorResponse(exception.msg))
        completeFrontendRequest(window, queuedRequestId, failedResponse)

proc bindFrontendCommands*(window: Window) =
  ## Installs the single WebUI binding used by every frontend command.
  if frontendRuntimeInitialized:
    raise newException(
      ValueError, "Frontend RPC is already bound to a window")

  if not frontendLocksInitialized:
    initLock(activeRequestIdsLock)
    initLock(frontendWakeLock)
    frontendLocksInitialized = true

  frontendRequestQueue.open()
  frontendWakeEvent = newAsyncEvent()
  frontendWindowOpen.store(true, moRelease)
  frontendRuntimeInitialized = true
  frontendWakeEvent.addEvent(
    proc(_: AsyncFD): bool {.gcsafe.} =
      false
  )

  window.bind("__invoke", proc(event: Event): string =
    let requestJson = event.getString()
    try:
      let (request, commandName, _) = frontendRequest(requestJson)
      if not frontendCommands.hasKey(commandName) or
          frontendCommands[commandName].kind == fckSynchronous:
        return dispatchFrontendRequest(requestJson)

      let id = requestId(request)
      if not reserveRequestId(id):
        return errorResponse("Duplicate frontend request ID '" & id & "'")
      if not queueFrontendRequest(requestJson):
        releaseRequestId(id)
        return errorResponse("The frontend RPC window is closed")
      result = acceptedResponse(id)
    except CatchableError as exception:
      result = errorResponse(exception.msg)
  )

  window.bind("", proc(event: Event) =
    if event.eventType == EventsDisconnected:
      acquire(frontendWakeLock)
      try:
        if frontendRuntimeInitialized:
          frontendWindowOpen.store(false, moRelease)
          frontendWakeEvent.trigger()
      finally:
        release(frontendWakeLock)
  )

proc runFrontendEventLoop*(window: Window) =
  ## Runs queued async commands and their completions on the main thread.
  if not frontendRuntimeInitialized:
    raise newException(
      ValueError, "bindFrontendCommands must be called before the event loop")

  while frontendWindowOpen.load(moAcquire):
    if not window.shown:
      frontendWindowOpen.store(false, moRelease)
      break
    startQueuedFrontendRequests(window)
    # FIX: A finite ceiling lets asyncdispatch honor its next timer deadline.
    poll(int32.high.int)

  acquire(frontendWakeLock)
  try:
    frontendRuntimeInitialized = false
    frontendWakeEvent.unregister()
    frontendWakeEvent.close()
    frontendRequestQueue.close()
  finally:
    release(frontendWakeLock)

  acquire(activeRequestIdsLock)
  try:
    activeRequestIds.clear()
  finally:
    release(activeRequestIdsLock)
