import std/[
  algorithm, asyncdispatch, asyncstreams, json, macros, math, options, os,
  sets, strutils, tables
]
import mustache

type
  FrontendCommandKind* = enum
    fckSynchronous
    fckAsynchronous
    fckStreaming

  FrontendTypeKind = enum
    ftkVoid
    ftkBoolean
    ftkString
    ftkNumber
    ftkNamed
    ftkSequence
    ftkArray
    ftkOption
    ftkTable
    ftkTuple

  FrontendType = ref object
    kind: FrontendTypeKind
    name: string
    elementType: FrontendType
    arrayLength: int
    fields: seq[FrontendField]

  FrontendField = object
    name: string
    fieldType: FrontendType

  BindingParameter = object
    nimName: string
    tsName: string
    parameterType: FrontendType
    hasDefault: bool

  FrontendBinding = object
    commandKind: FrontendCommandKind
    modulePath: string
    nimName: string
    tsName: string
    wireName: string
    parameters: seq[BindingParameter]
    returnType: FrontendType

  FrontendNamedTypeKind = enum
    fntObject
    fntEnum
    fntTuple

  TypeDeclaration = object
    identity: string
    name: string
    kind: FrontendNamedTypeKind
    fields: seq[FrontendField]
    members: seq[string]

  FrontendBindingsModel = object
    commands: seq[FrontendBinding]
    types: seq[TypeDeclaration]

var
  collectedBindings {.compileTime.}: seq[FrontendBinding]
  collectedTypes {.compileTime.}: seq[TypeDeclaration]

const GeneratedHeader = "// Generated by Nim {.accessible.}; do not edit.\n"
const MaxSafeJavaScriptInteger = 9_007_199_254_740_991'i64
const FrontendBindingsOutput {.strdefine.} = ""
const FrontendRpcProjectRoot = currentSourcePath().parentDir.parentDir.parentDir
const FrontendRpcMetadataPath =
  FrontendRpcProjectRoot / ".nimcache" / "nimri-rpc.json"
const CommandModuleTemplate = staticRead(
  currentSourcePath().parentDir / "nimri_rpc_templates" / "command.mustache")
const TypesTemplate = staticRead(
  currentSourcePath().parentDir / "nimri_rpc_templates" / "types.mustache")

include nimri_rpc/json_codec

include nimri_rpc/command_runtime

proc commandName(node: NimNode): string {.compileTime.} =
  case node.kind
  of nnkIdent, nnkSym:
    result = node.strVal
  of nnkPostfix:
    result = commandName(node[1])
  else:
    error("frontend only supports normally named procedures", node)

proc callableName(node: NimNode): NimNode {.compileTime.} =
  case node.kind
  of nnkIdent, nnkSym:
    result = node.copyNimTree
  of nnkPostfix:
    result = node[1].copyNimTree
  else:
    error("frontend only supports normally named procedures", node)

proc defaultInAdapterContext(node: NimNode;
    parameterValues: OrderedTable[string, NimNode]): NimNode {.compileTime.} =
  ## Default expressions are copied out of the procedure declaration and into
  ## the generated adapter. Make earlier converted/defaulted parameters
  ## available under their source names, letting Nim resolve identifiers inside
  ## the expression exactly as it normally would (including field names and
  ## nested scopes).
  result = newNimNode(nnkStmtListExpr)
  for name, value in parameterValues:
    result.add(newLetStmt(newIdentNode(name), value.copyNimTree))

  proc copyWithAdapterParameters(current: NimNode): NimNode =
    if current.kind == nnkSym and parameterValues.hasKey(current.strVal):
      return newIdentNode(current.strVal)
    result = current.copyNimNode
    for child in current:
      result.add(copyWithAdapterParameters(child))

  result.add(copyWithAdapterParameters(node))

proc lowerCamelCase(name: string): string {.compileTime.} =
  var uppercaseNext = false
  for character in name:
    if character == '_':
      uppercaseNext = true
    elif result.len == 0:
      result.add(character.toLowerAscii())
      uppercaseNext = false
    elif uppercaseNext:
      result.add(character.toUpperAscii())
      uppercaseNext = false
    else:
      result.add(character)

  if result.len == 0:
    error("frontend names cannot consist only of underscores")

proc isExportedName(node: NimNode): bool {.compileTime.} =
  node.kind == nnkPostfix and node.len == 2 and node[0].strVal == "*"

proc modulePathFor(filename: string): string {.compileTime.} =
  let
    source = filename.normalizedPath
    portableSource = source.replace(DirSep, '/')
    featuresMarker = "/features/"
    featureIndex = portableSource.rfind(featuresMarker)

  if featureIndex >= 0:
    let
      featureStart = featureIndex + featuresMarker.len
      commandsMarker = "/commands/"
      commandsIndex = portableSource.find(commandsMarker, featureStart)
    if commandsIndex < 0:
      error("accessible feature commands must be declared below a commands " &
        "directory", newLit(filename))
    result = portableSource[featureStart ..< commandsIndex]
    if result.len == 0:
      error("accessible commands require a non-empty feature path",
        newLit(filename))
  else:
    result = source.extractFilename.changeFileExt("")

proc replaceTypeParameters(typeNode: NimNode;
    replacements: Table[string, NimNode]): NimNode {.compileTime.} =
  if typeNode.kind in {nnkIdent, nnkSym} and
      replacements.hasKey(typeNode.strVal):
    return replacements[typeNode.strVal].copyNimTree

  result = typeNode.copyNimNode
  for child in typeNode:
    result.add(replaceTypeParameters(child, replacements))

proc wrappedValueType(typeNode, wrapper: NimNode): NimNode {.compileTime.} =
  let node =
    if typeNode.kind == nnkVarTy: typeNode[0]
    else: typeNode

  if node.kind == nnkBracketExpr and node.len == 2 and
      (node[0].sameType(wrapper) or node[0].eqIdent(wrapper.strVal)):
    return node[1]

  if node.kind == nnkBracketExpr and node.len > 1 and
      node[0].kind == nnkSym:
    let definition = node[0].getImpl
    if definition.kind == nnkTypeDef and
        definition[1].kind == nnkGenericParams and
        definition[1].len == node.len - 1:
      var replacements = initTable[string, NimNode]()
      for index, parameter in definition[1]:
        if parameter.kind notin {nnkIdent, nnkSym}:
          return newEmptyNode()
        replacements[parameter.strVal] = node[index + 1]
      return wrappedValueType(
        replaceTypeParameters(definition[2], replacements), wrapper)

  if node.kind == nnkSym:
    let definition = node.getImpl
    if definition.kind == nnkTypeDef:
      return wrappedValueType(definition[2], wrapper)

  result = newEmptyNode()

proc futureValueType(typeNode: NimNode): NimNode {.compileTime.} =
  wrappedValueType(typeNode, bindSym"Future")

proc futureStreamValueType(typeNode: NimNode): NimNode {.compileTime.} =
  wrappedValueType(typeNode, bindSym"FutureStream")

proc isVoidType(typeNode: NimNode): bool {.compileTime.} =
  if typeNode.kind in {nnkIdent, nnkSym} and typeNode.eqIdent("void"):
    return true
  if typeNode.kind == nnkSym:
    let definition = typeNode.getImpl
    if definition.kind == nnkTypeDef:
      return isVoidType(definition[2])

include nimri_rpc/frontend_types

macro collectFrontendBinding*(target: typed; modulePath, nimName,
    wireName: static[string]; commandKind: static[FrontendCommandKind]): untyped =
  let definition = target.getImpl
  if definition.kind != nnkProcDef:
    error("frontend binding metadata requires a procedure", target)

  let formalParams = definition[3]
  var
    binding = FrontendBinding(
      commandKind: commandKind,
      modulePath: modulePath,
      nimName: nimName,
      tsName: lowerCamelCase(nimName),
      wireName: wireName
    )
    tsParameterNames = initHashSet[string]()

  for index in 1 ..< formalParams.len:
    let parameter = formalParams[index]
    if parameter.kind != nnkIdentDefs:
      error("unsupported frontend command parameter", parameter)
    for nameIndex in 0 ..< parameter.len - 2:
      let
        originalName = parameter[nameIndex].strVal
        tsName = lowerCamelCase(originalName)
      if tsName in tsParameterNames:
        error("frontend parameter name collision after lowerCamelCase: '" &
          tsName & "'", parameter[nameIndex])
      tsParameterNames.incl(tsName)
      binding.parameters.add(BindingParameter(
        nimName: originalName,
        tsName: tsName,
        parameterType: frontendType(parameter[^2]),
        hasDefault: parameter[^1].kind != nnkEmpty
      ))

  let
    futureType = futureValueType(formalParams[0])
    streamType = futureStreamValueType(formalParams[0])
  binding.returnType = frontendType(
    case commandKind
    of fckSynchronous: formalParams[0]
    of fckAsynchronous: futureType
    of fckStreaming: streamType
  )

  for existing in collectedBindings:
    if existing.modulePath == binding.modulePath and
        existing.tsName == binding.tsName:
      error("frontend command name collision after lowerCamelCase in module '" &
        binding.modulePath & "': '" & binding.tsName & "'", target)
    if existing.wireName == binding.wireName:
      error("duplicate frontend wire name '" & binding.wireName & "'", target)

  collectedBindings.add(binding)
  result = newEmptyNode()

macro createFrontendCommandAdapter(target: typed; modulePath, nimName,
    wireName: static[string]): untyped =
  let
    definition = target.getImpl
    formalParams = definition[3]
    futureType = futureValueType(formalParams[0])
    streamType = futureStreamValueType(formalParams[0])
    commandKind =
      if streamType.kind != nnkEmpty: fckStreaming
      elif futureType.kind != nnkEmpty: fckAsynchronous
      else: fckSynchronous
    argsNode = genSym(nskParam, "args")

  if futureType.kind != nnkEmpty and
      futureStreamValueType(futureType).kind != nnkEmpty:
    error("accessible commands cannot return Future[FutureStream[T]]; " &
      "return FutureStream[T] directly", formalParams[0])

  if commandKind == fckStreaming:
    if isVoidType(streamType):
      error("accessible streaming commands cannot return FutureStream[void]",
        formalParams[0])
    if futureValueType(streamType).kind != nnkEmpty or
        futureStreamValueType(streamType).kind != nnkEmpty:
      error("accessible streaming command elements cannot be Future or " &
        "FutureStream values", formalParams[0])

  var
    adapterBody = newStmtList()
    call = newCall(target)
    parameterValues = initOrderedTable[string, NimNode]()

  for index in 1 ..< formalParams.len:
    let parameter = formalParams[index]
    if parameter.kind != nnkIdentDefs:
      error("unsupported frontend command parameter", parameter)

    let parameterType = parameter[^2]
    if parameterType.kind == nnkEmpty:
      error("accessible command parameters need an explicit type", parameter)
    let parameterTypeDescriptor =
      newTree(nnkBracketExpr, bindSym"typedesc", parameterType)

    for nameIndex in 0 ..< parameter.len - 2:
      let
        parameterNode = parameter[nameIndex]
        parameterName = commandName(parameterNode)
        parameterNameLiteral = newLit(parameterName)
        localValue = genSym(nskLet, parameterName)

      if parameter[^1].kind == nnkEmpty:
        adapterBody.add quote do:
          if not `argsNode`.hasKey(`parameterNameLiteral`):
            raise newException(ValueError,
              "Missing required argument '" & `parameterNameLiteral` & "'")
          let `localValue` = frontendFromJson(
            `argsNode`[`parameterNameLiteral`], `parameterTypeDescriptor`)
      else:
        let defaultValue =
          defaultInAdapterContext(parameter[^1], parameterValues)
        adapterBody.add quote do:
          let `localValue`: `parameterType` =
            if `argsNode`.hasKey(`parameterNameLiteral`):
              frontendFromJson(
                `argsNode`[`parameterNameLiteral`],
                `parameterTypeDescriptor`)
            else:
              `defaultValue`

      call.add(localValue)
      parameterValues[parameterName] = localValue

  result = newStmtList()
  result.add newCall(bindSym"collectFrontendBinding", target,
    newLit(modulePath), newLit(nimName), newLit(wireName),
    newLit(commandKind))

  if commandKind == fckStreaming:
    let
      stream = genSym(nskLet, "stream")
      item = genSym(nskLet, "item")
    adapterBody.add quote do:
      let `stream` = `call`
      if `stream`.isNil:
        raise newException(
          ValueError, "Accessible streaming command returned a nil stream")
      result = FrontendStream(
        readNext: proc(): Future[FrontendStreamRead] {.async.} =
          let `item` = await `stream`.read()
          if `item`[0]:
            result = FrontendStreamRead(
              hasValue: true,
              value: frontendToJson(`item`[1])
            ),
        cancel: proc() =
          if not `stream`.failed:
            `stream`.complete()
      )

    result.add quote do:
      registerFrontendStreamCommand(
        `wireName`,
        proc(`argsNode`: JsonNode): FrontendStream =
          `adapterBody`
      )
  elif commandKind == fckAsynchronous:
    if futureType.kind == nnkEmpty:
      error("internal error resolving asynchronous frontend result", target)
    elif isVoidType(futureType):
      adapterBody.add quote do:
        await `call`
        result = newJNull()
    else:
      let value = genSym(nskLet, "value")
      adapterBody.add quote do:
        let `value` = await `call`
        result = frontendToJson(`value`)

    result.add quote do:
      registerFrontendAsyncCommand(
        `wireName`,
        proc(`argsNode`: JsonNode): Future[JsonNode] {.async.} =
          `adapterBody`
      )
  else:
    if formalParams[0].kind == nnkEmpty:
      adapterBody.add(call)
      adapterBody.add quote do:
        result = newJNull()
    else:
      adapterBody.add quote do:
        result = frontendToJson(`call`)

    result.add quote do:
      registerFrontendSyncCommand(
        `wireName`,
        proc(`argsNode`: JsonNode): JsonNode =
          `adapterBody`
      )

macro accessible*(definition: untyped): untyped =
  ## Exposes a typed procedure through the frontend command registry and
  ## records its resolved signature for TypeScript generation.
  if definition.kind != nnkProcDef:
    error("accessible can only be applied to a procedure", definition)

  let genericParams = definition[2]
  if genericParams.kind != nnkEmpty and genericParams.len > 0:
    error("accessible commands cannot be generic", genericParams)

  let
    nimName = commandName(definition[0])
    target = callableName(definition[0])
    modulePath = modulePathFor(definition.lineInfoObj.filename)
    wireName = modulePath.replace('/', '.') & "." & nimName
  result = newStmtList(definition)
  result.add newCall(bindSym"createFrontendCommandAdapter", target,
    newLit(modulePath), newLit(nimName), newLit(wireName))

include nimri_rpc/bindings_generator
include nimri_rpc/sidecar_transport
