import std/[
  algorithm, asyncdispatch, atomics, json, locks, macros, math, options, os,
  sets, strutils, tables
]
import mustache
import webui

type
  FrontendCommandKind* = enum
    fckSynchronous
    fckAsynchronous

  FrontendTypeKind = enum
    ftkVoid
    ftkBoolean
    ftkString
    ftkNumber
    ftkNamed
    ftkSequence
    ftkArray
    ftkOption

  FrontendType = ref object
    kind: FrontendTypeKind
    name: string
    elementType: FrontendType

  BindingParameter = object
    nimName: string
    tsName: string
    parameterType: FrontendType
    hasDefault: bool

  FrontendBinding = object
    commandKind: FrontendCommandKind
    modulePath: string
    nimName: string
    tsName: string
    wireName: string
    parameters: seq[BindingParameter]
    returnType: FrontendType

  FrontendNamedTypeKind = enum
    fntObject
    fntEnum

  FrontendField = object
    name: string
    fieldType: FrontendType

  TypeDeclaration = object
    identity: string
    name: string
    kind: FrontendNamedTypeKind
    fields: seq[FrontendField]
    members: seq[string]

  FrontendBindingsModel = object
    commands: seq[FrontendBinding]
    types: seq[TypeDeclaration]

var
  collectedBindings {.compileTime.}: seq[FrontendBinding]
  collectedTypes {.compileTime.}: seq[TypeDeclaration]

const GeneratedHeader = "// Generated by Nim {.accessible.}; do not edit.\n"
const MaxSafeJavaScriptInteger = 9_007_199_254_740_991'i64
const FrontendBindingsOutput {.strdefine.} = ""
const FrontendRpcProjectRoot = currentSourcePath().parentDir.parentDir.parentDir
const FrontendRpcMetadataPath =
  FrontendRpcProjectRoot / ".nimcache" / "nimri-rpc.json"
const CommandModuleTemplate = staticRead(
  currentSourcePath().parentDir / "nimri_rpc_templates" / "command.mustache")
const TypesTemplate = staticRead(
  currentSourcePath().parentDir / "nimri_rpc_templates" / "types.mustache")

include nimri_rpc/json_codec

include nimri_rpc/command_runtime

proc commandName(node: NimNode): string {.compileTime.} =
  case node.kind
  of nnkIdent, nnkSym:
    result = node.strVal
  of nnkPostfix:
    result = commandName(node[1])
  else:
    error("frontend only supports normally named procedures", node)

proc callableName(node: NimNode): NimNode {.compileTime.} =
  case node.kind
  of nnkIdent, nnkSym:
    result = node.copyNimTree
  of nnkPostfix:
    result = node[1].copyNimTree
  else:
    error("frontend only supports normally named procedures", node)

proc defaultInAdapterContext(node: NimNode;
    parameterValues: OrderedTable[string, NimNode]): NimNode {.compileTime.} =
  ## Default expressions are copied out of the procedure declaration and into
  ## the generated adapter. Make earlier converted/defaulted parameters
  ## available under their source names, letting Nim resolve identifiers inside
  ## the expression exactly as it normally would (including field names and
  ## nested scopes).
  result = newNimNode(nnkStmtListExpr)
  for name, value in parameterValues:
    result.add(newLetStmt(newIdentNode(name), value.copyNimTree))

  proc copyWithAdapterParameters(current: NimNode): NimNode =
    if current.kind == nnkSym and parameterValues.hasKey(current.strVal):
      return newIdentNode(current.strVal)
    result = current.copyNimNode
    for child in current:
      result.add(copyWithAdapterParameters(child))

  result.add(copyWithAdapterParameters(node))

proc lowerCamelCase(name: string): string {.compileTime.} =
  var uppercaseNext = false
  for character in name:
    if character == '_':
      uppercaseNext = true
    elif result.len == 0:
      result.add(character.toLowerAscii())
      uppercaseNext = false
    elif uppercaseNext:
      result.add(character.toUpperAscii())
      uppercaseNext = false
    else:
      result.add(character)

  if result.len == 0:
    error("frontend names cannot consist only of underscores")

proc isExportedName(node: NimNode): bool {.compileTime.} =
  node.kind == nnkPostfix and node.len == 2 and node[0].strVal == "*"

proc commandsDirectory(): string {.compileTime.} =
  currentSourcePath().parentDir.parentDir / "commands"

proc modulePathFor(filename: string): string {.compileTime.} =
  let
    source = filename.normalizedPath
    root = commandsDirectory().normalizedPath
    relative = source.relativePath(root)

  if relative != ".." and not relative.startsWith("../") and
      not relative.startsWith(".." & $DirSep):
    result = relative.changeFileExt("").replace(DirSep, '/')
  else:
    let
      portableSource = source.replace(DirSep, '/')
      commandsMarker = "/commands/"
      markerIndex = portableSource.rfind(commandsMarker)
    if markerIndex >= 0:
      result = portableSource[
        markerIndex + commandsMarker.len .. ^1].changeFileExt("")
    else:
      result = source.extractFilename.changeFileExt("")

proc typeIdentity(symbol: NimNode): string {.compileTime.} =
  let location = symbol.getImpl.lineInfoObj
  result = location.filename.normalizedPath & ":" &
    $location.line & ":" & symbol.strVal

proc findType(identity: string): int {.compileTime.} =
  for index, declaration in collectedTypes:
    if declaration.identity == identity:
      return index
  result = -1

proc ensureNamedType(typeNode: NimNode): string {.compileTime.}

proc unsupportedType(typeNode: NimNode; detail = "") {.compileTime.} =
  var message = "unsupported frontend type '" & typeNode.repr & "'"
  if detail.len > 0:
    message.add(": " & detail)
  error(message, typeNode)

proc frontendType(typeNode: NimNode): FrontendType {.compileTime.} =
  if typeNode.kind == nnkEmpty:
    return FrontendType(kind: ftkVoid)

  let node =
    if typeNode.kind == nnkVarTy: typeNode[0]
    else: typeNode

  case node.kind
  of nnkBracketExpr:
    let container = node[0].strVal
    case container
    of "seq":
      if node.len != 2:
        unsupportedType(node)
      result = FrontendType(
        kind: ftkSequence,
        elementType: frontendType(node[1])
      )
    of "array":
      if node.len != 3:
        unsupportedType(node)
      result = FrontendType(
        kind: ftkArray,
        elementType: frontendType(node[2])
      )
    of "Option":
      if node.len != 2:
        unsupportedType(node)
      result = FrontendType(
        kind: ftkOption,
        elementType: frontendType(node[1])
      )
    else:
      unsupportedType(node,
        "generics are not part of the frontend binding contract")
  of nnkSym, nnkIdent:
    let name = node.strVal
    case name
    of "void":
      result = FrontendType(kind: ftkVoid)
    of "bool":
      result = FrontendType(kind: ftkBoolean)
    of "string":
      result = FrontendType(kind: ftkString)
    of "int", "int8", "int16", "int32", "int64",
        "uint", "uint8", "uint16", "uint32", "uint64",
        "Natural", "Positive", "float", "float32", "float64":
      result = FrontendType(kind: ftkNumber)
    else:
      if node.kind != nnkSym:
        unsupportedType(node, "the type could not be resolved")
      let typeName = ensureNamedType(node)
      result = FrontendType(kind: ftkNamed, name: typeName)
  of nnkTupleTy, nnkTupleConstr:
    unsupportedType(node, "tuples are not supported")
  of nnkRefTy:
    unsupportedType(node, "reference types are not supported")
  of nnkPtrTy:
    unsupportedType(node, "pointer types are not supported")
  else:
    unsupportedType(node)

proc futureValueType(typeNode: NimNode): NimNode {.compileTime.} =
  let node =
    if typeNode.kind == nnkVarTy: typeNode[0]
    else: typeNode

  if node.kind == nnkBracketExpr and node.len == 2 and
      node[0].sameType(bindSym"Future"):
    return node[1]

  if node.kind == nnkSym:
    let definition = node.getImpl
    if definition.kind == nnkTypeDef:
      return futureValueType(definition[2])

  result = newEmptyNode()

proc enumMemberName(node: NimNode): string {.compileTime.} =
  case node.kind
  of nnkIdent, nnkSym:
    result = node.strVal
  of nnkEnumFieldDef:
    result = node[0].strVal
  else:
    error("unsupported enum member in frontend type", node)

proc ensureNamedType(typeNode: NimNode): string {.compileTime.} =
  let
    identity = typeIdentity(typeNode)
    existingIndex = findType(identity)

  if existingIndex >= 0:
    return collectedTypes[existingIndex].name

  let definition = typeNode.getImpl
  if definition.kind != nnkTypeDef:
    unsupportedType(typeNode)
  if not isExportedName(definition[0]):
    error("frontend object and enum types must be exported: '" &
      typeNode.strVal & "'", typeNode)

  let
    typeName = typeNode.strVal
    body = definition[2]

  for declaration in collectedTypes:
    if declaration.name == typeName and declaration.identity != identity:
      error("ambiguous frontend type name '" & typeName &
        "' is declared in more than one module", typeNode)

  # Install a placeholder first so recursive object fields terminate.
  collectedTypes.add(TypeDeclaration(identity: identity, name: typeName))
  let declarationIndex = collectedTypes.high

  case body.kind
  of nnkEnumTy:
    collectedTypes[declarationIndex].kind = fntEnum
    for index in 1 ..< body.len:
      collectedTypes[declarationIndex].members.add(
        enumMemberName(body[index]))
    if collectedTypes[declarationIndex].members.len == 0:
      error("frontend enums must contain at least one member", typeNode)
  of nnkObjectTy:
    collectedTypes[declarationIndex].kind = fntObject
    if body[1].kind != nnkEmpty:
      error("frontend objects cannot use inheritance", typeNode)
    let fields = body[2]
    if fields.kind != nnkRecList:
      error("unsupported frontend object layout for '" & typeName & "'",
        typeNode)

    for field in fields:
      if field.kind != nnkIdentDefs:
        error("frontend objects cannot contain variants or case fields",
          field)
      if field[^1].kind != nnkEmpty:
        error("frontend object fields cannot have default values", field)
      for nameIndex in 0 ..< field.len - 2:
        let fieldNameNode = field[nameIndex]
        if not isExportedName(fieldNameNode):
          error("frontend object field '" & commandName(fieldNameNode) &
            "' must be exported", fieldNameNode)
        let
          fieldName = commandName(fieldNameNode)
          fieldType = frontendType(field[^2])
        collectedTypes[declarationIndex].fields.add(
          FrontendField(name: fieldName, fieldType: fieldType))
  else:
    unsupportedType(typeNode,
      "only exported enums and plain objects are supported as named types")

  result = typeName

macro collectFrontendBinding*(target: typed; modulePath, nimName,
    wireName: static[string]; commandKind: static[FrontendCommandKind]): untyped =
  let definition = target.getImpl
  if definition.kind != nnkProcDef:
    error("frontend binding metadata requires a procedure", target)

  let formalParams = definition[3]
  var
    binding = FrontendBinding(
      commandKind: commandKind,
      modulePath: modulePath,
      nimName: nimName,
      tsName: lowerCamelCase(nimName),
      wireName: wireName
    )
    tsParameterNames = initHashSet[string]()

  for index in 1 ..< formalParams.len:
    let parameter = formalParams[index]
    if parameter.kind != nnkIdentDefs:
      error("unsupported frontend command parameter", parameter)
    for nameIndex in 0 ..< parameter.len - 2:
      let
        originalName = parameter[nameIndex].strVal
        tsName = lowerCamelCase(originalName)
      if tsName in tsParameterNames:
        error("frontend parameter name collision after lowerCamelCase: '" &
          tsName & "'", parameter[nameIndex])
      tsParameterNames.incl(tsName)
      binding.parameters.add(BindingParameter(
        nimName: originalName,
        tsName: tsName,
        parameterType: frontendType(parameter[^2]),
        hasDefault: parameter[^1].kind != nnkEmpty
      ))

  let futureType = futureValueType(formalParams[0])
  binding.returnType = frontendType(
    if commandKind == fckAsynchronous: futureType
    else: formalParams[0]
  )

  for existing in collectedBindings:
    if existing.modulePath == binding.modulePath and
        existing.tsName == binding.tsName:
      error("frontend command name collision after lowerCamelCase in module '" &
        binding.modulePath & "': '" & binding.tsName & "'", target)
    if existing.wireName == binding.wireName:
      error("duplicate frontend wire name '" & binding.wireName & "'", target)

  collectedBindings.add(binding)
  result = newEmptyNode()

macro createFrontendCommandAdapter(target: typed; modulePath, nimName,
    wireName: static[string]): untyped =
  let
    definition = target.getImpl
    formalParams = definition[3]
    futureType = futureValueType(formalParams[0])
    commandKind =
      if futureType.kind == nnkEmpty: fckSynchronous
      else: fckAsynchronous
    argsNode = genSym(nskParam, "args")

  var
    adapterBody = newStmtList()
    call = newCall(target)
    parameterValues = initOrderedTable[string, NimNode]()

  for index in 1 ..< formalParams.len:
    let parameter = formalParams[index]
    if parameter.kind != nnkIdentDefs:
      error("unsupported frontend command parameter", parameter)

    let parameterType = parameter[^2]
    if parameterType.kind == nnkEmpty:
      error("accessible command parameters need an explicit type", parameter)
    let parameterTypeDescriptor =
      newTree(nnkBracketExpr, bindSym"typedesc", parameterType)

    for nameIndex in 0 ..< parameter.len - 2:
      let
        parameterNode = parameter[nameIndex]
        parameterName = commandName(parameterNode)
        parameterNameLiteral = newLit(parameterName)
        localValue = genSym(nskLet, parameterName)

      if parameter[^1].kind == nnkEmpty:
        adapterBody.add quote do:
          if not `argsNode`.hasKey(`parameterNameLiteral`):
            raise newException(ValueError,
              "Missing required argument '" & `parameterNameLiteral` & "'")
          let `localValue` = frontendFromJson(
            `argsNode`[`parameterNameLiteral`], `parameterTypeDescriptor`)
      else:
        let defaultValue =
          defaultInAdapterContext(parameter[^1], parameterValues)
        adapterBody.add quote do:
          let `localValue`: `parameterType` =
            if `argsNode`.hasKey(`parameterNameLiteral`):
              frontendFromJson(
                `argsNode`[`parameterNameLiteral`],
                `parameterTypeDescriptor`)
            else:
              `defaultValue`

      call.add(localValue)
      parameterValues[parameterName] = localValue

  result = newStmtList()
  result.add newCall(bindSym"collectFrontendBinding", target,
    newLit(modulePath), newLit(nimName), newLit(wireName),
    newLit(commandKind))

  if commandKind == fckAsynchronous:
    if futureType.kind == nnkEmpty:
      error("internal error resolving asynchronous frontend result", target)
    elif futureType.strVal == "void":
      adapterBody.add quote do:
        await `call`
        result = newJNull()
    else:
      let value = genSym(nskLet, "value")
      adapterBody.add quote do:
        let `value` = await `call`
        result = frontendToJson(`value`)

    result.add quote do:
      registerFrontendAsyncCommand(
        `wireName`,
        proc(`argsNode`: JsonNode): Future[JsonNode] {.async.} =
          `adapterBody`
      )
  else:
    if formalParams[0].kind == nnkEmpty:
      adapterBody.add(call)
      adapterBody.add quote do:
        result = newJNull()
    else:
      adapterBody.add quote do:
        result = frontendToJson(`call`)

    result.add quote do:
      registerFrontendSyncCommand(
        `wireName`,
        proc(`argsNode`: JsonNode): JsonNode =
          `adapterBody`
      )

macro accessible*(definition: untyped): untyped =
  ## Exposes a typed procedure through the frontend command registry and
  ## records its resolved signature for TypeScript generation.
  if definition.kind != nnkProcDef:
    error("accessible can only be applied to a procedure", definition)

  let genericParams = definition[2]
  if genericParams.kind != nnkEmpty and genericParams.len > 0:
    error("accessible commands cannot be generic", genericParams)

  let
    nimName = commandName(definition[0])
    target = callableName(definition[0])
    modulePath = modulePathFor(definition.lineInfoObj.filename)
    wireName = modulePath.replace('/', '.') & "." & nimName
  result = newStmtList(definition)
  result.add newCall(bindSym"createFrontendCommandAdapter", target,
    newLit(modulePath), newLit(nimName), newLit(wireName))

include nimri_rpc/bindings_generator
include nimri_rpc/webui_bridge
