// Generated by Nim {.accessible.}; do not edit.
import type { Greeting } from './types';
import { invoke } from '../rpc';

export function greet(name: string): Promise<Greeting> {
  return invoke<Greeting>('greeting.greet', { name });
}
