// Generated by Nim {.accessible.}; do not edit.
import type { someType } from './types';
import { invoke } from '../rpc';

export function abctest(something: someType): Promise<string> {
  return invoke<string>('greeting.abctest', { something });
}
