// Generated by Nim {.accessible.}; do not edit.
import type { starwars } from './types';
import { invoke } from '../rpc';

export function somefunction(sw: starwars): Promise<string> {
  return invoke<string>('other.somefunction', { sw });
}
